word_list = ['beard ', 'hair ', 'beard.', 'hair.', 'beards;', 'hair;',
             'bearded', 'hairy', 
             'boy', 'girl', 
             'brother', 'sister', 
             'Dad', 'Mom', ' dad;', ' mom;', ' dad.', ' mom.', ' dad?', ' mom?', 'Daddy', 'Mommy', 
             'emperor', 'empress', 
             'Farmer Maggot', 'Alexandria', 
             'father', 'mother', 'Father', 'Mother', 
             'fellow', 'sister', 
             'greybeards', 'greyhairs', 
             ' he ', ' she ', 'He ', 'She ', ' he,', ' she,', ' he;', 'she;', ' he:', ' she:', '(he ', '(she ', ' he)', ' she)', ' he.', ' she.', ' he?', ' she?', '\nhe ', '\nshe ', "he'd", "she'd", "he'll", "she'll", "He'll", "She'll", "he's", "she's", "He's", "She's", 
             'him ', ' her ', 'Him', 'Her', ' him,', ' her,', ' him;', ' her;', ' him:', ' her:', '(him ', '(her ', ' him)', ' her)', ' him.', ' her.', ' him?', ' her?', ' him!', ' her!', '\nhim ', '\n her ', '\nhim,', '\nher,', 'himself', 'herself', ' his ', ' her ', 'His', 'Her', ' his,', ' her,', '(his ', '(her ', '\nhis ', '\nher ', 
             ' king', ' queen', 'King', 'Queen', '-king', '-queen', ' 
             'lad ', ' lass ', ' lad,', ' lass,', ' lads ', ' lasses ', ' lads,', ' lasses', 
             'Ladies', 'Lords', 'lady', 'lord', 'Lady', 'Lord', 
             'man ', 'woman ', 'Man ', 'Woman ', 'man,', 'woman,', 'man;', 'woman;', 'man:', 'woman:', 'man)', 'woman)', 'man.', 'woman.', 'man?', 'woman?', 'Man?', 'Woman?', 'Man!', 'Woman!', 'manned', 'womanned', 'manwise', 'womanwise', 'men ', 'women ', 'Men', 'Women', ' men,', ' women,', ' men.', ' women.', ' men!', ' women!', " men:", " women:", " men's", " women's", 
             'Mr.', 'Miss', 'Mrs.', 'Miss', 'Miss Maggot', 'Kerry', 
             'nephew', 'niece', 
             ' sir ', ' madam ', ' sir,', ' madam,',  ' sir\'', ' madam\'', ' sir.', ' madam.', ' sir!', ' madam!', 
             'prince ', 'princess ', 'Prince', 'Princess', 'princes ', 'princesses ', 
             'sistership', 'sisterhood', 
             ' son ', ' daughter ', ' son,', ' daughter,', ' son.', ' daughter.', ' sons', ' daughters', 
             'uncle', 'aunt', 'Uncle', 'Aunt', 
             'wowoman', 'woman', 'wowomen', 'women']
